create table IF NOT EXISTS `USERS`
(
`user_id` INTEGER generated by default as identity primary key,
`email` varchar not null unique,
`login` varchar not null unique,
`name` varchar not null unique,
`birthday` timestamp not null
);

create table IF NOT EXISTS `FRIENDS`
(
`friend_pair_id` INTEGER generated by default as identity primary key,
`user_id` integer references USERS(user_id),
`friend_id` integer references USERS(user_id)
);

create table IF NOT EXISTS `MPA`
(
`mpa_id` INTEGER generated by default as identity primary key,
`name` varchar(10) not null
);

create table IF NOT EXISTS `FILMS`
(
`film_id` INTEGER generated by default as identity primary key,
`name` varchar not null,
`description` varchar not null,
`releaseDate` timestamp not null,
`duration` integer not null,
`mpa_id` integer not null references `MPA`(mpa_id),
`rate` integer
);

create table IF NOT EXISTS `FAVOURITE_FILM`
(
`favourite_film_id` INTEGER generated by default as identity primary key,
`film_id` integer references FILMS(film_id),
`user_id` integer references USERS(user_id)
);

create table IF NOT EXISTS `GENRES`
(
`genre_id` INTEGER generated by default as identity primary key,
`name` varchar not null
);

create table IF NOT EXISTS `GENRE_AND_FILM`
(
`genre_and_film_id` INTEGER generated by default as identity primary key,
`film_id` integer references FILMS(film_id),
`genre_id` integer references GENRES(genre_id)
);


