create table USERS
(
user_id integer generated by default as identity primary key,
email varchar not null,
login varchar not null,
name varchar not null,
birthday timestamp not null
);

create table CONFIRMED_INVATE
(
confirmed_invate_id integer generated by default as identity primary key,
user_id integer references USERS(user_id),
friend_id integer references USERS(user_id)
);

create table UNCONFIRMED_INVATE
(
unconfirmed_invate_id integer generated by default as identity primary key,
user_id integer references USERS(user_id),
friend_id integer references USERS(user_id)
);

create table FILMS
(
film_id integer generated by default as identity primary key,
name varchar not null,
description varchar not null,
releaseDate timestamp not null,
duration integer not null,
rating varchar not null
);

create table FAVOURITE_FILM
(
favourite_film_id integer generated by default as identity primary key,
film_id integer references FILMS(film_id),
user_id integer references USERS(user_id)
);

create table GENRES
(
genres_id integer generated by default as identity primary key,
title varchar not null,
description varchar not null
);

create table GENRE_AND_FILM
(
genre_and_film_id integer generated by default as identity primary key,
film_id integer references FILMS(film_id),
genre_id integer references GENRES(genres_idw)
);

